version: '3.8'

services:
  jellyfin-signup:
    build:
      context: .
      dockerfile: Dockerfile.simple
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production