version: '3.8'

services:
  jellyfin-signup:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /data/compose/1/nginx/data/logs:/npm-logs:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=development
